spring.application.name=budgetAi

#db
spring.jpa.hibernate.ddl-auto=update

# Endereço e chave da Groq
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}

# Modelo da Groq
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.temperature=0.7

spring.ai.model.audio.transcription=openai
spring.ai.openai.audio.transcription.options.model=whisper-large-v3
spring.ai.openai.audio.transcription.options.language=pt
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.prompt=Áudio em português brasileiro. \
  Áudio contém descrições de gastos financeiros. As frases geralmente contem: \
    - Um valor em reais (R$) ou centavos (¢) \
    - Uma ação (ex: "paguei", "comprei", "gastei", "recebi") \
    - Um local ou estabelecimento (ex: "mercado", "restaurante", "Uber", "farmácia")


spring.ai.model.audio.speech=openai
# orpheus-v1-english gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.model=canopylabs/orpheus-v1-english
spring.ai.openai.audio.speech.options.voice=austin
spring.ai.openai.audio.speech.options.response-format=wav
spring.ai.openai.audio.speech.options.speed=1.2